#!/usr/bin/env bash
# Teardown / uninstall what setup-project.sh created in a code project.
# Symmetric counterpart to setup-project.sh:
#   - removes .claude/, .codex/, .codegraph/ (entirely created by setup)
#   - removes the .gitignore block we appended (or whole file if we created it)
#   - removes root-level CLAUDE.md / AGENTS.md ONLY when they match the
#     project-init template fingerprint (customized files are preserved)
#   - .claude/settings.local.json is preserved by default (may carry user
#     permissions); pass --purge-config to remove
#
# ⚠️  DESTRUCTIVE — this script DELETES files. By default it asks before
#   removing anything that could be user content. Pass --yes to skip prompts.
#   Use --dry-run to preview without touching disk.
#
# Usage:
#   teardown-project.sh [directory]                     # interactive
#   teardown-project.sh [directory] --yes               # skip confirmations
#   teardown-project.sh [directory] --dry-run           # audit only
#   teardown-project.sh [directory] --keep-config       # keep root CLAUDE.md/AGENTS.md + settings.local.json
#   teardown-project.sh [directory] --purge-config      # also remove settings.local.json (if it looks like ours)
#   teardown-project.sh [directory] --backup            # tar.gz a backup of what will be removed
#
# Exit codes:
#   0 - all targeted items cleaned
#   1 - directory not found or no project-init artifacts present
#   2 - user aborted or partial failure

set -euo pipefail

TARGET=""
YES=false
DRY_RUN=false
KEEP_CONFIG=false
PURGE_CONFIG=false
BACKUP=false

for arg in "$@"; do
    case "$arg" in
        --yes|-y)         YES=true ;;
        --dry-run|-n)     DRY_RUN=true ;;
        --keep-config|-k) KEEP_CONFIG=true ;;
        --purge-config)   PURGE_CONFIG=true ;;
        --backup|-b)      BACKUP=true ;;
        --help|-h)
            sed -n '2,30p' "$0"
            exit 0
            ;;
        -*)
            echo "❌ 未知选项: $arg" >&2
            exit 2
            ;;
        *)
            TARGET="$arg"
            ;;
    esac
done

TARGET="${TARGET:-$PWD}"
SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"

if [[ ! -d "$TARGET" ]]; then
    echo "❌ Directory does not exist: $TARGET"
    exit 1
fi

cd "$TARGET"
TARGET_ABS="$PWD"

echo "🧹 Teardown project: $TARGET_ABS"
[[ "$DRY_RUN" == true ]]   && echo "   Mode: DRY-RUN (no changes)"
[[ "$KEEP_CONFIG" == true ]] && echo "   Mode: keep-config (preserve CLAUDE.md / AGENTS.md / settings.local.json)"
[[ "$PURGE_CONFIG" == true ]] && echo "   Mode: purge-config (remove settings.local.json if it matches)"
[[ "$BACKUP" == true ]]    && echo "   Mode: backup (archive before removal)"
[[ "$YES" == true ]]       && echo "   Mode: assume-yes"

# ══════════════════════════════════════════════════════════════════════════
# PHASE 1: AUDIT
# ══════════════════════════════════════════════════════════════════════════
echo ""
echo "📋 Phase 1: Audit"

INIT_DONE=false
[[ -f ".claude/.init-done" ]] && INIT_DONE=true

if [[ "$INIT_DONE" == false && ! -d ".claude" && ! -d ".codex" && ! -d ".codegraph" && ! -f "CLAUDE.md" && ! -f "AGENTS.md" ]]; then
    echo "   (no project-init artifacts found — nothing to teardown)"
    exit 1
fi

REMOVE_DIRS=()        # always removed (wholly created by setup)
REMOVE_FILES=()       # always removed (clearly project-init output)
AMBIENT_DIRS=()       # removed unless --keep-config
AMBIENT_FILES=()      # removed unless --keep-config (fingerprint matched)
USER_FILES=()         # removed only with --yes (no fingerprint match — risky)
SKIP_NOTES=()         # informational, not removed

# .claude/ — wholly created
if [[ -d ".claude" ]]; then
    REMOVE_DIRS+=(".claude")
fi

# .codex/ — wholly created (contains AGENTS.md we wrote)
if [[ -d ".codex" ]]; then
    REMOVE_DIRS+=(".codex")
fi

# .codegraph/ — generated by `codegraph init`
if [[ -d ".codegraph" ]]; then
    REMOVE_DIRS+=(".codegraph")
fi

# CLAUDE.md — fingerprint check
if [[ -f "CLAUDE.md" ]]; then
    if grep -qF "This file provides working guidance for Claude Code when contributing to this repository." "CLAUDE.md" \
       && grep -qF "## Plan 文件镜像（重要）" "CLAUDE.md"; then
        if [[ "$KEEP_CONFIG" == true ]]; then
            SKIP_NOTES+=("CLAUDE.md (--keep-config, matches project-init template)")
        else
            REMOVE_FILES+=("CLAUDE.md")
        fi
    else
        if [[ "$KEEP_CONFIG" == true ]]; then
            SKIP_NOTES+=("CLAUDE.md (--keep-config, user-customized)")
        else
            USER_FILES+=("CLAUDE.md (no project-init fingerprint — likely user content)")
        fi
    fi
fi

# AGENTS.md — fingerprint check
if [[ -f "AGENTS.md" ]]; then
    if grep -qF "This file provides guidance to Codex and other coding agents" "AGENTS.md" \
       && grep -qF "## Plan 文件镜像（重要）" "AGENTS.md"; then
        if [[ "$KEEP_CONFIG" == true ]]; then
            SKIP_NOTES+=("AGENTS.md (--keep-config, matches project-init template)")
        else
            REMOVE_FILES+=("AGENTS.md")
        fi
    else
        if [[ "$KEEP_CONFIG" == true ]]; then
            SKIP_NOTES+=("AGENTS.md (--keep-config, user-customized)")
        else
            USER_FILES+=("AGENTS.md (no project-init fingerprint — likely user content)")
        fi
    fi
fi

# .claude/settings.local.json — only remove with --purge-config, and only if it
# matches the project-init template shape (only "default" permissions)
if [[ -f ".claude/settings.local.json" ]]; then
    if [[ "$PURGE_CONFIG" == true ]]; then
        # Check fingerprint: only contains the recommended permission set
        if python3 -c "
import json, sys
with open('.claude/settings.local.json') as f:
    data = json.load(f)
allow = set(data.get('permissions', {}).get('allow', []))
expected = {
    'Bash(npm:*)', 'Bash(npx:*)', 'Bash(yarn:*)', 'Bash(pnpm:*)', 'Bash(bun:*)',
    'Bash(pip:*)', 'Bash(pip3:*)', 'Bash(python:*)', 'Bash(python3:*)',
    'Bash(node:*)', 'Bash(go:*)', 'Bash(cargo:*)', 'Bash(rustc:*)',
    'Bash(javac:*)', 'Bash(mvn:*)', 'Bash(gradle:*)',
    'Bash(make:*)', 'Bash(cmake:*)', 'Bash(xcodebuild:*)', 'Bash(swift:*)',
    'Bash(git:*)', 'Bash(curl:*)', 'Bash(codegraph:*)',
    'Bash(ls:*)', 'Bash(cat:*)', 'Bash(find:*)', 'Bash(grep:*)', 'Bash(wc:*)',
    'Bash(which:*)', 'Bash(echo:*)', 'Bash(mkdir:*)', 'Bash(cd:*)',
    'Read(*)', 'Edit(*)', 'Write(*)', 'WebFetch(*)', 'WebSearch(*)'
}
if data.get('plansDirectory') == '.claude/plans' and allow == expected:
    sys.exit(0)
sys.exit(1)
" 2>/dev/null; then
            REMOVE_FILES+=(".claude/settings.local.json")
        else
            USER_FILES+=(".claude/settings.local.json (--purge-config requested, but file has user-customized permissions)")
        fi
    else
        SKIP_NOTES+=(".claude/settings.local.json (pass --purge-config to remove)")
    fi
fi

# .gitignore — strip our block (or remove file if we created it whole)
GITIGNORE_HAS_BLOCK=false
GITIGNORE_WHOLE=false
if [[ -f ".gitignore" ]]; then
    if grep -qF "# project-init generated local agent files" ".gitignore"; then
        GITIGNORE_HAS_BLOCK=true
        # Was the file created entirely by us? Heuristic: file is small (≤ 7 lines)
        # and contains no content other than the header + 5 entries
        if [[ $(wc -l < ".gitignore") -le 7 ]]; then
            GITIGNORE_WHOLE=true
        fi
    fi
fi

# ── Print audit ─────────────────────────────────────────────────────────
if [[ ${#REMOVE_DIRS[@]} -gt 0 ]]; then
    echo ""
    echo "   Directories to remove (created by setup):"
    for d in "${REMOVE_DIRS[@]}"; do
        echo "     - $d/"
    done
fi

if [[ ${#REMOVE_FILES[@]} -gt 0 ]]; then
    echo ""
    echo "   Files to remove (created by setup):"
    for f in "${REMOVE_FILES[@]}"; do
        echo "     - $f"
    done
fi

if [[ "$GITIGNORE_HAS_BLOCK" == true ]]; then
    echo ""
    if [[ "$GITIGNORE_WHOLE" == true ]]; then
        echo "   .gitignore to remove (entire file created by setup)"
    else
        echo "   .gitignore to modify (strip project-init block only)"
    fi
fi

if [[ ${#USER_FILES[@]} -gt 0 ]]; then
    echo ""
    echo "   ⚠ Files that look like USER content (not touched unless --yes):"
    for f in "${USER_FILES[@]}"; do
        echo "     - $f"
    done
fi

if [[ ${#SKIP_NOTES[@]} -gt 0 ]]; then
    echo ""
    echo "   Skipped (preserved):"
    for s in "${SKIP_NOTES[@]}"; do
        echo "     - $s"
    done
fi

if [[ ${#REMOVE_DIRS[@]} -eq 0 && ${#REMOVE_FILES[@]} -eq 0 && "$GITIGNORE_HAS_BLOCK" == false && ${#USER_FILES[@]} -eq 0 ]]; then
    echo ""
    echo "   (nothing to remove)"
    exit 0
fi

# ══════════════════════════════════════════════════════════════════════════
# PHASE 2: CONFIRM
# ══════════════════════════════════════════════════════════════════════════
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Count actions
ACTION_COUNT=0
[[ ${#REMOVE_DIRS[@]}  -gt 0 ]] && ACTION_COUNT=$((ACTION_COUNT + ${#REMOVE_DIRS[@]}))
[[ ${#REMOVE_FILES[@]} -gt 0 ]] && ACTION_COUNT=$((ACTION_COUNT + ${#REMOVE_FILES[@]}))
[[ "$GITIGNORE_HAS_BLOCK" == true ]] && ACTION_COUNT=$((ACTION_COUNT + 1))
[[ ${#USER_FILES[@]} -gt 0 && "$YES" == true ]] && ACTION_COUNT=$((ACTION_COUNT + ${#USER_FILES[@]}))

echo "⚠  About to perform $ACTION_COUNT destructive action(s)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [[ "$DRY_RUN" == true ]]; then
    echo ""
    echo "🔍 DRY-RUN: no changes made. Re-run without --dry-run to apply."
    exit 0
fi

if [[ "$YES" != true ]]; then
    echo ""
    read -r -p "Continue? [y/N] " ans
    case "$ans" in
        y|Y|yes|YES) ;;
        *) echo "❌ Aborted."; exit 2 ;;
    esac
fi

# ══════════════════════════════════════════════════════════════════════════
# PHASE 3: BACKUP (optional)
# ══════════════════════════════════════════════════════════════════════════
if [[ "$BACKUP" == true ]]; then
    TS="$(date -u +%Y%m%dT%H%M%SZ)"
    ARCHIVE="$TARGET_ABS/.project-init-backup-$TS.tar.gz"
    echo ""
    echo "📦 Creating backup: $ARCHIVE"

    BACKUP_ARGS=()
    for d in "${REMOVE_DIRS[@]}"; do
        [[ -e "$d" ]] && BACKUP_ARGS+=("$d")
    done
    for f in "${REMOVE_FILES[@]}"; do
        [[ -e "$f" ]] && BACKUP_ARGS+=("$f")
    done
    [[ "$GITIGNORE_HAS_BLOCK" == true && -f ".gitignore" ]] && BACKUP_ARGS+=(".gitignore")
    [[ ${#USER_FILES[@]} -gt 0 && "$YES" == true ]] && for f in "${USER_FILES[@]}"; do
        path="${f%% *}"
        [[ -e "$path" ]] && BACKUP_ARGS+=("$path")
    done

    if [[ ${#BACKUP_ARGS[@]} -gt 0 ]]; then
        tar -czf "$ARCHIVE" "${BACKUP_ARGS[@]}" 2>/dev/null
        echo "   ✓ Archived ${#BACKUP_ARGS[@]} item(s)"
    fi
fi

# ══════════════════════════════════════════════════════════════════════════
# PHASE 4: REMOVE
# ══════════════════════════════════════════════════════════════════════════
echo ""
echo "🗑  Phase 4: Remove"

REMOVED=0
FAILED=0

remove_dir() {
    local d="$1"
    if [[ -d "$d" ]]; then
        if rm -rf "$d" 2>/dev/null; then
            echo "   ✓ removed $d/"
            REMOVED=$((REMOVED + 1))
        else
            echo "   ✗ failed to remove $d/" >&2
            FAILED=$((FAILED + 1))
        fi
    fi
}

remove_file() {
    local f="$1"
    if [[ -f "$f" ]]; then
        if rm -f "$f" 2>/dev/null; then
            echo "   ✓ removed $f"
            REMOVED=$((REMOVED + 1))
        else
            echo "   ✗ failed to remove $f" >&2
            FAILED=$((FAILED + 1))
        fi
    fi
}

# Directories first (so we never try to remove files inside them)
if [[ ${#REMOVE_DIRS[@]} -gt 0 ]]; then
    for d in "${REMOVE_DIRS[@]}"; do
        remove_dir "$d"
    done
fi

# Files
if [[ ${#REMOVE_FILES[@]} -gt 0 ]]; then
    for f in "${REMOVE_FILES[@]}"; do
        remove_file "$f"
    done
fi

# .gitignore: strip block or remove whole file
if [[ "$GITIGNORE_HAS_BLOCK" == true ]]; then
    if [[ "$GITIGNORE_WHOLE" == true ]]; then
        remove_file ".gitignore"
    else
        # Surgically remove the project-init block
        if python3 << 'PYEOF'
import os
path = ".gitignore"
marker = "# project-init generated local agent files"
with open(path) as f:
    content = f.read()
if marker not in content:
    raise SystemExit(0)

idx = content.find(marker)
# Walk back to also consume a leading blank line that we added during append
start = idx
if start > 0 and content[start-1] == '\n':
    start -= 1
    if start > 0 and content[start-1] == '\n':
        start -= 1

prefix = content[:start]
# Normalize: strip trailing whitespace, keep single trailing newline
prefix = prefix.rstrip() + '\n' if prefix.strip() else ''

with open(path, 'w') as f:
    f.write(prefix)
PYEOF
        then
            echo "   ✓ stripped project-init block from .gitignore"
            REMOVED=$((REMOVED + 1))
        else
            echo "   ✗ failed to strip .gitignore block" >&2
            FAILED=$((FAILED + 1))
        fi
    fi
fi

# User-flagged files (only with --yes)
if [[ "$YES" == true && ${#USER_FILES[@]} -gt 0 ]]; then
    for entry in "${USER_FILES[@]}"; do
        path="${entry%% *}"
        remove_file "$path"
    done
fi

# ══════════════════════════════════════════════════════════════════════════
# PHASE 5: CLEANUP / SUMMARY
# ══════════════════════════════════════════════════════════════════════════
# Best-effort codegraph index cleanup (no-op if CLI missing)
if command -v codegraph &> /dev/null && [[ ! -d ".codegraph" ]]; then
    codegraph clean "$TARGET_ABS" >/dev/null 2>&1 || true
fi

# Clean up empty parent dirs (.claude, .codex) if anything was left
for d in .claude .codex .codegraph; do
    if [[ -d "$d" ]] && [[ -z "$(ls -A "$d" 2>/dev/null)" ]]; then
        rmdir "$d" 2>/dev/null || true
    fi
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [[ $FAILED -eq 0 ]]; then
    echo "✅ Teardown complete — $REMOVED item(s) removed"
else
    echo "⚠  Teardown finished with $FAILED error(s) — $REMOVED removed"
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [[ ${#USER_FILES[@]} -gt 0 && "$YES" != true ]]; then
    echo ""
    echo "ℹ  Skipped (USER content, no fingerprint):"
    for f in "${USER_FILES[@]}"; do
        echo "   - $f"
    done
    echo "   Re-run with --yes to remove these too (destructive)."
fi

if [[ "$BACKUP" == true && -f ".project-init-backup-"*.tar.gz ]]; then
    echo ""
    echo "📦 Backup saved in project root: .project-init-backup-*.tar.gz"
fi

exit $((FAILED > 0 ? 1 : 0))
